import { Canteen } from "./types";

export const CANTEENS: Canteen[] = [
  {
    id: "green-bowl",
    name: "The Green Bowl",
    cuisine: "Salads & Health",
    rating: 4.8,
    ratingCount: 120,
    deliveryTime: "12-18 min",
    deliveryOnly: false,
    priceLevel: "$$",
    currency: "$",
    location: "Main Campus",
    tags: ["Healthy", "Clean-Eating", "Sustainable"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAlEmDDKf-sUcv45kZOIGW9qh2lBBBNPuCQS4cYRTWJ-UXdOY_QtE3ujTV62DCid0H_4v4u7VY88T-Dz0fpwYSVLagFIPGyhheF91xVA8S7AkmSnw580smHmkuPbaJPII808Qlg-_3pHN_G9klHN-RS8n-P4866anU7J-DdLSJOIl3vH47OOGSSM3goEK3VaHBbadMf_i5mFv796ciovVxDE-dLOwLwANu2N7N19-nrvWicS2IW7pi8Gh70UDQtpGzXkQi7ne2Qgv8",
    menu: [
      {
        id: "harvest-bowl",
        name: "Harvest Power Bowl",
        description: "Quinoa base, massaged kale, roasted sweet potatoes, avocado, and toasted pumpkin seeds with ginger-miso dressing.",
        price: 12.50,
        kcal: 420,
        isVegan: true,
        isGlutenFree: true,
        isBestseller: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmkeCucTydr_Y1pMrZXRRqCYiIYMNt4Epo0mwF24V3ydTJPSL62bRt-oYgLe9u7U5EKwQFnnX8SoKkf7W20nX9lvnSJ9v4R7mOznhP9anpZlTnpfPT5sB_WKpx45rZfgilR6XsooyI0OhDvePcN7uAvdFK0hE_e9j-imfebioKlEtmX9UTH4S1FLZQrmvbQGpzOffiRuKqcrnjPdjI7LJDFeACYricdA0TsnrXPnKErzBCEEg67-SBQpkpIz2IzltLQD-rQ5N32gA",
      },
      {
        id: "falafel-wrap",
        name: "Spiced Falafel Wrap",
        description: "House-made herb falafel, pickled radish, cucumber, and tahini drizzle in a whole-wheat wrap.",
        price: 9.00,
        kcal: 580,
        isVegan: true,
        isGlutenFree: false,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAhIfggAP5bPxrzgnI_ol_Ckujg1wm9FIvnBVfImHyr2ahDY5jv3htn5L7OiqEmMBVD7D8gEX8c87L5TQsbNz-TBQuz2P58edjRHwaT8owFMIR2XckSRaAupKaEKamwnPmXgB75meUT6s7X8pIpYHr03HOsDh1C2ZMtloQc82nn_YZCtZg1xJ3ZG-q5qnfn_gCEL5363fOSjLbfkyCCBIpfhiI_mZXP2AZ33I8S0CuDvh_9Kb5XjKtz6hiLiG9eHEhwMMpvepBtc2I",
      },
      {
        id: "miso-tofu",
        name: "Miso Tofu Salad",
        description: "Charred miso tofu, snap peas, and ginger vinaigrette on mixed greens.",
        price: 11.25,
        kcal: 310,
        isVegan: false,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1-stUwo6_D1CnLmhhL3sKAJBXHFfVHADe8efhQmtmKDBgnGuNOOo0f60t7Y-pIZirvOr9tismmFIXSFaBMy8oz24XULcBaEWpuMZdUdjkeh-m-qbLSwF9AYJbyh6c7IXNJxFlEmkUnsXQO6geySSins80FIu4CSoxfs3T-YNBjauXm3KvVA3giirXgJjSmvDVSuE_HjaBcE5Csl-lLTAlx-vlVV7spCAtJbNHjgEgSCtn7B7dvcQAjuyZ9Jqu25PEf1LC_pl5plw",
      },
      {
        id: "turmeric-soup",
        name: "Golden Turmeric Soup",
        description: "Anti-inflammatory lentil and turmeric soup served with a slice of sourdough toast.",
        price: 6.50,
        kcal: 290,
        isVegan: true,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD7P2FFWaaxndrMS2JDCaTmGDtqnkvwa9aLQr4FumbJvVbatYHx4sBUM-q9xITI1advIEuriIK_Gkt9XdqD0Z_PCx_bBu1hoeSFWV99C2ZUA2j5aqQsAzICloHTxlZ7tjxXQPUeW4JNqf2ticxK7cDU1PHnkQ-dpP1Ip8LeS5y3wTQNY4Nb0nBl8sw8NMAgLqlAadZCUqr4ekn_epMP8MmXhGOKqQMR4SLrtEwzsEcEGOVgrD_zMrlWAx6aSH6TIwnFTyRoEuMvUlo",
      },
      {
        id: "umami-tofu",
        name: "Umami Tofu Plate",
        description: "Miso-glazed tofu, steamed seasonal greens, and brown rice with sesame seeds.",
        price: 10.50,
        kcal: 450,
        isVegan: true,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAQCdxZ3IKFMr1_Vp6InBZ6Gm2pTjmfjTe8f6KXyKVUduCnbGXtuFMCfaM7qNvCFBudj7nKM11ovz4cJ6KcNKkxa1p68ixlz9onTAUH0r-K87INU51RWF-xZ5u5kbOunRPqHkWeIOUQJXdPdKBTqBah6rCY0_CuZURzmsr_FIUv-oM3AM6dSup9-iFANo1j18-R_LVdTCjcBMs92r6yf9oIhjzlgc9f00KJNvDnOLWT5U9RjNK3t1-fxfm-iPiBZk-4Ys8b2FnQ8lg",
      },
      {
        id: "mediterranean-quinoa",
        name: "Mediterranean Quinoa",
        description: "Kalamata olives, feta, cherry tomatoes, and cucumber over fluffy quinoa.",
        price: 9.50,
        kcal: 380,
        isVegan: false,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5WEU3okpru9GR1bMXkf99jzkMGrPzcBGNEDdz3y2wTX42qziSbDc2h76v3g-Fns15V0o8vpJCEhQkVW_e4IUnlK8i9wCMwCIgn3ChwAlfBHdUJUI8eyeo_Ci-Fs1pMTv7VZeK2lcAVgeUYknz1uE3guVWyLl-xa7Ue4MITLa7U6yRsojpM5g8jH2b6fYBuxA9SHqod8zPSqtZfD2TXDSCHIKL5LVCQp7lMVztMxEPKk65laiIZrdqO4f2EZb5z6LwwOCMdx_-4Mg",
      }
    ]
  },
  {
    id: "main-hall-bistro",
    name: "Main Hall Bistro",
    cuisine: "Healthy & Gluten-Free",
    rating: 4.8,
    ratingCount: 240,
    deliveryTime: "10-15 min",
    deliveryOnly: false,
    priceLevel: "$$$",
    currency: "$",
    location: "Engineering Block",
    tags: ["Healthy", "Gluten-Free", "Premium"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzw_5-WBhm9M0HO8uJrISdcTFq4pSVIPwkdQxMe_WH146_e7mKLGV0Oe82J6pUIT81gSNUx4wvp7tOqPxMz_bhbNCyaSCZFxboOPhxSGU6fFm-ldWovb99JAIZV0ZJO2ZgyfyPmueuZL_geaJKcL0mjb8nyXBvBIn_my4KahQh69UtKHNZ3mUqwe3LZcp9y7_T-0bJf3bA8ny3jopdqC9vEJlq7ob1XMo0hUxsbgm2fD8T-jfgWcJDv3oAqpCGcjJ-pxsRvwnSaa0",
    menu: [
      {
        id: "avocado-bowl",
        name: "Avocado Zest Bowl",
        description: "Quinoa base, loaded with avocado slices, kale, roasted seeds, and light vinaigrette.",
        price: 12.50,
        kcal: 410,
        isVegan: true,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCtKzUNu15CJd6Hy8M55-mI3vG1Sv64_J4WAX62yVcbJvSdo2se247t2mJ8XTsAYsPnozGQKxeB5AzRxsL_6uKVfElyy36pBgbKURxCqQ90rPs9x9Kk0PTDhiJNdy7rZ8TIexnaeFGWVo_6vh0bnQ3s4Q7Ayq3DW2SXOALaYiBmMBeCovnq4fnqWNZxYtbAIe-XgxXoMyCOIFFJlxYXWEUs2nY_0MeEnevpjzcm29RFCmzRF0PzvpUtQem2nqRnxEiLIagO5fvbEH4",
      },
      {
        id: "salmon-plate",
        name: "Grilled Salmon Plate",
        description: "Mediterranean-style grilled salmon served alongside vibrant roasted seasonal vegetables.",
        price: 15.99,
        kcal: 480,
        isVegan: false,
        isGlutenFree: true,
        isBestseller: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzw_5-WBhm9M0HO8uJrISdcTFq4pSVIPwkdQxMe_WH146_e7mKLGV0Oe82J6pUIT81gSNUx4wvp7tOqPxMz_bhbNCyaSCZFxboOPhxSGU6fFm-ldWovb99JAIZV0ZJO2ZgyfyPmueuZL_geaJKcL0mjb8nyXBvBIn_my4KahQh69UtKHNZ3mUqwe3LZcp9y7_T-0bJf3bA8ny3jopdqC9vEJlq7ob1XMo0hUxsbgm2fD8T-jfgWcJDv3oAqpCGcjJ-pxsRvwnSaa0",
      },
      {
        id: "harvest-toast-usd",
        name: "Avocado Harvest Toast",
        description: "Poached eggs, sourdough bread, creamy avocado mash, and a hint of fresh chili flakes.",
        price: 12.50,
        kcal: 420,
        isVegan: false,
        isGlutenFree: false,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDZaMU2_0UvtQ0WEEc3cdIIj8b4sJt2g7KZccZEVhco28WyxoXs309BsAZjEM-IDKcL-0hvHKDS7yXqlyXm46hddNcNBqvnVSm_Y0AJNJUw8V17oqvoh1J8EO3CY42fOoZ0OvCidGR7Pmxe8FgZLnqzOSn38T7MnZtR9knmzmn-XBXDhYQJPo64rENqqqQpDL3qPrUKTWpqfmnphuMmrAlqISZazCzdvCpPexGMntpZiEvyqqRNdX-3faa5owmrCxmF1qa5e7tMLOE"
      }
    ]
  },
  {
    id: "burger-loft",
    name: "The Burger Loft",
    cuisine: "Fast Food",
    rating: 4.5,
    ratingCount: 185,
    deliveryTime: "5-10 min",
    deliveryOnly: true,
    priceLevel: "$$",
    currency: "$",
    location: "Engineering Block",
    tags: ["Burgers", "Fast Food", "Bestsellers"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuApvR7aXjMxjvX_5DHH-wyyGIRLLmKTW5udL2ALHjocQYDEDbF0jx62yDqeU0LKBMVFBBNp-3Y_6BTEmVQOBzOTWlDT2Zt1-KdTXXZsfj0QNU3UdLLvm2ZHixn7cnU1q_1c4jQVU5j86MuQdG8ni_mX51fyUrx5rf1QlMgeVuK0ZTW1ejSr1-deY_-pU521GLTLDKasq8Vo5UzUHwiJ5M5Hfy3wUTBgGel1D6fw3zmEQPFJ52kuKofXRkkJ03oBh2YCS-YDmgY5uOo",
    menu: [
      {
        id: "classic-burger",
        name: "Classic Loft Burger",
        description: "Prime beef patty, melted cheddar cheese, lettuce, tomatoes, and home-style loft sauce.",
        price: 9.50,
        kcal: 620,
        isVegan: false,
        isGlutenFree: false,
        isBestseller: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuApvR7aXjMxjvX_5DHH-wyyGIRLLmKTW5udL2ALHjocQYDEDbF0jx62yDqeU0LKBMVFBBNp-3Y_6BTEmVQOBzOTWlDT2Zt1-KdTXXZsfj0QNU3UdLLvm2ZHixn7cnU1q_1c4jQVU5j86MuQdG8ni_mX51fyUrx5rf1QlMgeVuK0ZTW1ejSr1-deY_-pU521GLTLDKasq8Vo5UzUHwiJ5M5Hfy3wUTBgGel1D6fw3zmEQPFJ52kuKofXRkkJ03oBh2YCS-YDmgY5uOo",
      },
      {
        id: "pepperoni-pizza",
        name: "Rustic Pepperoni Pizza",
        description: "Hand-stretched thin crust, marinara, rich pepperoni, and bubbly mozzarella with fresh basil.",
        price: 14.00,
        kcal: 680,
        isVegan: false,
        isGlutenFree: false,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDKn7-jYuOO9aj_Do-B40BsgfVLzWKHw_DdZCMRgoEFBVQaUFWaw2FkuVmgUYm6aEO_tEaIk-2khaFOrEoL7uSpTIH2KU2q6nNGIh4jfkCKPMxpUxwFekNO1THxWjs_Swi6hiXGQNJzhrcG2c7zCX4P0w05TzAmx4hAV1pLc2O2R9vp39tlVsOcBltXhky_qxXs5e19OKgEosW5GZ_rdhmQd2oGeDR7N6c5lH-UNKHGSXsONkhUEf_lm768bpaOOxCN8moNkFTYoiw",
      }
    ]
  },
  {
    id: "atrium-brew",
    name: "The Atrium Brew",
    cuisine: "Artisan Coffee",
    rating: 4.9,
    ratingCount: 310,
    deliveryTime: "5-10 min",
    deliveryOnly: false,
    priceLevel: "$",
    currency: "$",
    location: "Main Campus",
    tags: ["Coffee", "Bakery", "Brewed"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSKKm1KobhG84fnNOEK9OlOsZIo_s-OWdIL18L2XohQU6vnrTAs-_eoUCBguVXNxREZ_f0-ds1NnLv-WvsMgGpkV0bf00ziwOUJzjL0GqX_43wPWMGaVK6qDr_VfirIRMsxfPweyYWZaRh_x4RPbeXId6yFVE59_ODVVWbu0ZMT2VD5LN_lzFECjt5bqtTDlTVYNvdynFiEM5LHw6wLRO0r52Jh_svQJzIJyjNnM0dcHQs2SteD_FyvfHyxkuRfDvBUqIxwlXHF50",
    menu: [
      {
        id: "matcha-latte",
        name: "Iced Matcha Latte",
        description: "Craft barista matcha green tea layered perfectly with creamy, organic oat milk.",
        price: 5.50,
        kcal: 180,
        isVegan: true,
        isGlutenFree: true,
        isBestseller: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBRZYgwudZPeoH0t2q9OSUnPdkpmsD9BuvfF85oc4cv1W3Zs79O6Fms11nGbJ3cY0JtP_udKEmaiY-j8qdoaGAXZWVPGxC6Bm7C-vIjz8cadPUjtm4KAHSuR08Ucc9l-vfSfhMqjRPVHzTDxNMdFLA_ERrXZrzIuK4sqrWL4xQorfNpwM9iqc040NjqoYN1UACGRrwr7owKXMRs10-9a-mMPklyhE-Js-VkSDGbI3GRf2n3TQP2tjGaWqKP1OZoezWJ33Ova3MaUT0",
      },
      {
        id: "honey-donut",
        name: "Honey Glaze Donut Box",
        description: "Assorted mini donuts, perfectly glazed with organic golden honey.",
        price: 3.50,
        kcal: 350,
        isVegan: false,
        isGlutenFree: false,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBCxwPoZyw9FxAQE9URvcQFp27-saOTRuCLTY4GXYR2m4dRjEgFxoT6xZM2lciGFGNXsHhw7sdhKPuoys5dUiujIwU9n2E4J-9edAGirTQWJdE7OcIOODEJ78r5FvAsl7OCnp6wAKUH_RlYZyso3JM3EMcB5LKcgocjc3W0WBWtO0Y9tsehfy2SAt_LSvL3ETmFFzIfzB9UHde_rhuPEfOXhQu3tsB2t0BPuSr-01hwFu6F_za0smhaut0w97hm9Hd5iWDaGQItoWI",
      }
    ]
  },
  {
    id: "north-wing-cafe",
    name: "North Wing Cafe",
    cuisine: "Asian Fusion",
    rating: 4.8,
    ratingCount: 190,
    deliveryTime: "15-20 min",
    deliveryOnly: false,
    priceLevel: "$$",
    currency: "$",
    location: "Library West Wing",
    tags: ["Asian", "Stir-fry", "Sushi"],
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAL8BbbeIoZnrEsqgKXFR1cKVwN1aTT03KbgTALyjqSCSmm2aaLg9-2RoNH0Y7UauNqbAcw4din0sIBvj9X29D6ZDO7iA1UoMZcNOZH_meUrKd6ORKD4bLl6qxtkkOqAlsjsRYW3YmXyjQq3cveKI2ZFrDOjMDxJIFht8JC-6OsyWhEWx5RZS_dtx8znUbJ0O-_7BOEZsJznZZlooYF4KdTW46AMU7teGR4Rzv8Dva5l665YODbkCKI1uEIywu0pG8aFDCWqSMo_VU",
    menu: [
      {
        id: "tofu-stirfry",
        name: "Tofu Stir-fry Bowl",
        description: "Golden brown pan-fried tofu, crispy snap peas, carrots, ginger, and garlic glaze over brown rice.",
        price: 11.50,
        kcal: 490,
        isVegan: true,
        isGlutenFree: true,
        isBestseller: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-gE39UU48ns4gV52uOAWfTt47FjrUg6VyE25Kfwn4LhIgNnzgeTCrtsRswhO1WyZ1kMBpyot4BGv7BHGkIOgfUsB_et5_XJl2xrWZ7y3wuvYDu1YIrTSrGxzZSl92Qozw3fQnSXig59nVMH4Y_SHCTwIyVdRbqgLIbFYGnVUbW3Bt_AyqcaoVHIu4xlwnzTe0VrQeHNfy06N-VjHmAVPwTEHOXV-Mkd57MxW2IZ8Y7UMkMu5eAYtLD0YUM63F9y5fiABAcvA33wI",
      },
      {
        id: "salmon-zen-bowl",
        name: "Salmon Zen Bowl",
        description: "Fresh sesame-seared salmon, avocado slices, edamame over seasoned jasmine rice.",
        price: 14.50,
        kcal: 520,
        isVegan: false,
        isGlutenFree: true,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAE0596ALmR0i3-xDd-18R6ikkgPq2XD8hgHHDase-wgPDopjeXV9-FNTg7k8jSbcYyB5DWd_54UbgiHN8HdOeMUvoQuMF6-PiSliOz8aRjujXbVSb0J97Xe92GQZ5iVMaeGuyZH6449pP2_HZ_bOmawZto43j-vktvDeTFhoVJLNxbvU3axWOUnyEs2e0C3Ktc0Qvx9L-k0FakzZ3CMJChRDYXaHYV-pyOxPlKZJOO_54HmX7EWHUmg7w56OrqCSUz9GvhsYi1L04",
      }
    ]
  }
];

export const CATEGORIES = [
  { id: "pizza", name: "Pizza", icon: "Pizza" },
  { id: "bowls", name: "Bowls", icon: "Salad" },
  { id: "coffee", name: "Coffee", icon: "Coffee" },
  { id: "salads", name: "Salads", icon: "Leaf" },
  { id: "desserts", name: "Desserts", icon: "IceCream" },
  { id: "drinks", name: "Drinks", icon: "Milk" }
];
